### ISSUE TITLE
How changes template for gallery

### ISSUE THREAD

**Issue by atomoc** [rjchauhan/Light-Gallery-for-OctoberCMS#7]
In folder **rjgallery/components/gallery/** have one file **default.html**, whether it is possible to create your own templates? If yes to how?

**Comment by rjchauhan** [comment]
Yes, you can.

To do this you have to modify **default.html** as you like. **default.html** is the file which is loaded when you initialize the plugin component.

**Comment by rjchauhan** [comment]
Or also you can do overwrite the **default.html** file by creating the folder in partials with the same name as the plugin component name. and there you can add extra code.

For example: `partials\gallery\default.html`

You have the access to all variables that are passed in **default.html** file by component.

Add your own design and done.
